sudo: required
service:
  - docker

before_install:
 - docker build -t farizbenchaoui/docker-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true farizbenchaoui/docker-test npm run test 


after_sucess:
#don't have to specify the dockerfile as the default will be used
 - docker build -t farizbenchaoui/multi-client ./client
 - docker build -t farizbenchaoui/multi-server ./server
 - docker build -t farizbenchaoui/multi-nginx  ./nginx
 - docker build -t farizbenchaoui/multi-worker ./worker

 #log in to docker cli
 #add password to standard in, then do the login process saying expect password in stdin
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub
 - docker push farizbenchaoui/multi-client
 - docker push farizbenchaoui/multi-server
 - docker push farizbenchaoui/multi-nginx
 - docker push farizbenchaoui/multi-worker